- name: configure dispatch server
  hosts: dispatch
  become: yes
  tasks:
  - name: app setup
    include_role:
      name: common
      tasks_from: app-setup

  - name: golang setup
    include_role:
      name: common
      tasks_from: go

  - name: systemd setup
    include_role:
    name: common
    tasks_from: systemd.yaml