- name: Install golang
  ansible.builtin.package:
    name: golang
    state: present
 
- name: Initialize Go module
  ansible.builtin.command: go mod init dispatch
  args:
    chdir: /app

- name: Get Go dependencies
  ansible.builtin.command: go get
  args:
    chdir: /app

- name: Build Go application
  ansible.builtin.command: go build
  args:
    chdir: /app